from __future__ import annotations

from pathlib import Path
from typing import Any, Literal


class LibertyDocument:
    @property
    def library_name(self) -> str: ...
    def cells(self) -> list[str]: ...
    def cell(self, name: str) -> Cell: ...
    def bus_types(self) -> list[str]: ...
    def bus_type(self, name: str) -> BusType: ...
    def timing_tables(
        self,
        *,
        cell: str | None = None,
        pin: str | None = None,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
        table: str | None = None,
    ) -> list[dict[str, Any]]: ...
    def to_polars(
        self,
        kind: Literal["timing"] = "timing",
        **filters: Any,
    ) -> Any: ...


class Cell:
    @property
    def name(self) -> str: ...
    @property
    def area(self) -> float | None: ...
    def pins(self) -> list[str]: ...
    def pin(self, name: str) -> Pin: ...
    def buses(self) -> list[str]: ...
    def bus(self, name: str) -> Bus: ...
    def bundles(self) -> list[str]: ...
    def bundle(self, name: str) -> Bundle: ...


class Pin:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def function(self) -> str | None: ...
    def timing_arcs(
        self,
        *,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
    ) -> list[TimingArc]: ...


class Bus:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def function(self) -> str | None: ...
    @property
    def bus_type(self) -> str | None: ...
    def pins(self) -> list[str]: ...
    def pin(self, name: str) -> Pin: ...
    def timing_arcs(
        self,
        *,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
    ) -> list[TimingArc]: ...


class Bundle:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def function(self) -> str | None: ...
    @property
    def members(self) -> list[str]: ...
    def pins(self) -> list[str]: ...
    def pin(self, name: str) -> Pin: ...
    def timing_arcs(
        self,
        *,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
    ) -> list[TimingArc]: ...


class BusType:
    @property
    def name(self) -> str: ...
    def attributes(self) -> dict[str, str]: ...
    def get(self, key: str) -> str | None: ...


class TimingArc:
    @property
    def related_pin(self) -> str | None: ...
    @property
    def timing_type(self) -> str | None: ...
    @property
    def when(self) -> str | None: ...
    def tables(self) -> list[str]: ...
    def table(self, name: str) -> TimingTable: ...


class TimingTable:
    @property
    def name(self) -> str: ...
    @property
    def index_1(self) -> list[float]: ...
    @property
    def index_2(self) -> list[float]: ...
    @property
    def values(self) -> list[float]: ...
    def to_polars(self) -> Any: ...


def parse_file(path: str | Path, **filters: Any) -> LibertyDocument: ...
