from __future__ import annotations

from pathlib import Path
from typing import Any, Literal


class LibertyDocument:
    @property
    def library_name(self) -> str: ...
    @property
    def voltage_unit(self) -> str | None: ...
    @property
    def current_unit(self) -> str | None: ...
    @property
    def time_unit(self) -> str | None: ...
    @property
    def capacitive_load_unit(self) -> str | None: ...
    def templates(self) -> dict[str, list[str | None]]: ...
    def attributes(self) -> list[tuple[str, str]]: ...
    def driver_waveforms(self) -> list[TimingTable]: ...
    def energy_unit_joules(self) -> float | None: ...
    def cells(self) -> list[str]: ...
    def cell(self, name: str) -> Cell: ...
    def bus_types(self) -> list[str]: ...
    def bus_type(self, name: str) -> BusType: ...
    def timing_tables(
        self,
        *,
        cell: str | None = None,
        pin: str | None = None,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
        table: str | None = None,
    ) -> list[dict[str, Any]]: ...
    def internal_power_tables(
        self,
        *,
        cell: str | None = None,
        pin: str | None = None,
        related_pin: str | None = None,
        related_pg_pin: str | None = None,
        when: str | None = None,
        table: str | None = None,
    ) -> list[dict[str, Any]]: ...
    def to_polars(
        self,
        kind: Literal["timing", "power"] = "timing",
        **filters: Any,
    ) -> Any: ...


class BooleanExpression:
    def __init__(self, source: str) -> None: ...
    @property
    def source(self) -> str: ...
    @property
    def raw(self) -> str: ...
    @property
    def variables(self) -> list[str]: ...
    def minterms(self) -> list[str]: ...
    def canonical(self) -> str: ...
    def minimized(self) -> str: ...
    def eval(self, mapping: dict[str, bool] | None = ..., **kwargs: bool) -> bool: ...
    def implies(self, other: BooleanExpression) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class Cell:
    @property
    def name(self) -> str: ...
    @property
    def area(self) -> float | None: ...
    def pins(self) -> list[str]: ...
    def pin(self, name: str) -> Pin: ...
    def buses(self) -> list[str]: ...
    def bus(self, name: str) -> Bus: ...
    def bundles(self) -> list[str]: ...
    def bundle(self, name: str) -> Bundle: ...
    def attributes(self) -> list[tuple[str, str]]: ...
    def dynamic_currents(self) -> list[DynamicCurrent]: ...
    def ff(self) -> Ff | None: ...
    def latch(self) -> Latch | None: ...


class Pin:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def function(self) -> str | None: ...
    @property
    def three_state(self) -> str | None: ...
    @property
    def power_down_function(self) -> str | None: ...
    def function_expr(self) -> BooleanExpression | None: ...
    def three_state_expr(self) -> BooleanExpression | None: ...
    def power_down_function_expr(self) -> BooleanExpression | None: ...
    def timing_arcs(
        self,
        *,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
    ) -> list[TimingArc]: ...
    def internal_power(
        self,
        *,
        related_pin: str | None = None,
        related_pg_pin: str | None = None,
        when: str | None = None,
    ) -> list[InternalPower]: ...
    def attributes(self) -> list[tuple[str, str]]: ...


class Bus:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def function(self) -> str | None: ...
    def function_expr(self) -> BooleanExpression | None: ...
    @property
    def bus_type(self) -> str | None: ...
    def pins(self) -> list[str]: ...
    def pin(self, name: str) -> Pin: ...
    def timing_arcs(
        self,
        *,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
    ) -> list[TimingArc]: ...


class Bundle:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str | None: ...
    @property
    def function(self) -> str | None: ...
    def function_expr(self) -> BooleanExpression | None: ...
    @property
    def members(self) -> list[str]: ...
    def pins(self) -> list[str]: ...
    def pin(self, name: str) -> Pin: ...
    def timing_arcs(
        self,
        *,
        related_pin: str | None = None,
        timing_type: str | None = None,
        when: str | None = None,
    ) -> list[TimingArc]: ...


class BusType:
    @property
    def name(self) -> str: ...
    def attributes(self) -> dict[str, str]: ...
    def get(self, key: str) -> str | None: ...


class TimingArc:
    @property
    def related_pin(self) -> str | None: ...
    @property
    def timing_type(self) -> str | None: ...
    @property
    def when(self) -> str | None: ...
    @property
    def sdf_cond(self) -> str | None: ...
    def when_expr(self) -> BooleanExpression | None: ...
    def sdf_cond_expr(self) -> BooleanExpression | None: ...
    def tables(self) -> list[str]: ...
    def table(self, name: str) -> TimingTable: ...


class InternalPower:
    @property
    def related_pin(self) -> str | None: ...
    @property
    def related_pg_pin(self) -> str | None: ...
    @property
    def when(self) -> str | None: ...
    def when_expr(self) -> BooleanExpression | None: ...
    def tables(self) -> list[str]: ...
    def table(self, name: str) -> TimingTable: ...


class DynamicCurrent:
    @property
    def related_inputs(self) -> str | None: ...
    @property
    def related_outputs(self) -> str | None: ...
    @property
    def when(self) -> str | None: ...
    def when_expr(self) -> BooleanExpression | None: ...
    def switching_groups(self) -> list[SwitchingGroup]: ...


class SwitchingGroup:
    @property
    def input_switching_condition(self) -> str | None: ...
    @property
    def output_switching_condition(self) -> str | None: ...
    def input_switching_expr(self) -> BooleanExpression | None: ...
    def output_switching_expr(self) -> BooleanExpression | None: ...
    def pg_currents(self) -> list[PgCurrent]: ...


class Ff:
    @property
    def variable1(self) -> str | None: ...
    @property
    def variable2(self) -> str | None: ...
    @property
    def next_state(self) -> str | None: ...
    @property
    def clocked_on(self) -> str | None: ...
    @property
    def clocked_on_also(self) -> str | None: ...
    @property
    def clear(self) -> str | None: ...
    @property
    def preset(self) -> str | None: ...
    @property
    def power_down_function(self) -> str | None: ...
    def next_state_expr(self) -> BooleanExpression | None: ...
    def clocked_on_expr(self) -> BooleanExpression | None: ...
    def clocked_on_also_expr(self) -> BooleanExpression | None: ...
    def clear_expr(self) -> BooleanExpression | None: ...
    def preset_expr(self) -> BooleanExpression | None: ...
    def power_down_function_expr(self) -> BooleanExpression | None: ...


class Latch:
    @property
    def variable1(self) -> str | None: ...
    @property
    def variable2(self) -> str | None: ...
    @property
    def enable(self) -> str | None: ...
    @property
    def data_in(self) -> str | None: ...
    @property
    def clear(self) -> str | None: ...
    @property
    def preset(self) -> str | None: ...
    def enable_expr(self) -> BooleanExpression | None: ...
    def data_in_expr(self) -> BooleanExpression | None: ...
    def clear_expr(self) -> BooleanExpression | None: ...
    def preset_expr(self) -> BooleanExpression | None: ...


class PgCurrent:
    @property
    def pg_pin(self) -> str | None: ...
    def vectors(self) -> list[TimingTable]: ...


class TimingTable:
    @property
    def name(self) -> str: ...
    @property
    def index_1(self) -> list[float]: ...
    @property
    def index_2(self) -> list[float]: ...
    @property
    def index_3(self) -> list[float]: ...
    @property
    def values(self) -> list[float]: ...
    @property
    def template(self) -> str | None: ...
    @property
    def reference_time(self) -> float | None: ...
    def vectors(self) -> list[TimingTable]: ...
    def to_polars(self) -> Any: ...


class LibraryIndex:
    @classmethod
    def open(cls, path: str | Path) -> LibraryIndex: ...
    @property
    def library_name(self) -> str: ...
    @property
    def voltage_unit(self) -> str | None: ...
    @property
    def current_unit(self) -> str | None: ...
    @property
    def time_unit(self) -> str | None: ...
    @property
    def capacitive_load_unit(self) -> str | None: ...
    def energy_unit_joules(self) -> float | None: ...
    def templates(self) -> dict[str, list[str | None]]: ...
    def attributes(self) -> list[tuple[str, str]]: ...
    def driver_waveforms(self) -> list[TimingTable]: ...
    def cell_names(self) -> list[str]: ...
    def num_cells(self) -> int: ...
    def cell(self, name: str) -> Cell: ...


def parse_file(path: str | Path, **filters: Any) -> LibertyDocument: ...
